# Generated by Django 5.1.6 on 2025-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('isAdults', models.BooleanField()),
            ],
        ),
    ]
