# Generated by Django 5.1.6 on 2025-03-16 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('about', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('body', models.TextField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testApp.games')),
            ],
        ),
    ]
