# Generated by Django 5.1.6 on 2025-03-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_games_rating_count_user_rating_count_alter_games_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating_count',
        ),
    ]
