# Generated by Django 5.1.6 on 2025-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_remove_games_rating_count_remove_user_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='testApp.genres'),
        ),
        migrations.DeleteModel(
            name='GameGenre',
        ),
    ]
