# Generated by Django 5.1.6 on 2025-03-26 20:55

import django.db.models.deletion
import testApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_usergame_last_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to=testApp.models.game_media_path)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='testApp.games')),
            ],
        ),
    ]
