# Generated by Django 5.1.6 on 2025-04-28 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_alter_games_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='achievements',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergame',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergame',
            name='time_played',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
