# Generated by Django 5.1.6 on 2025-05-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_gamegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameGenre',
        ),
    ]
